### ISSUE TITLE
js configuration

### ISSUE THREAD

**Issue by mtamony** [Pushwoosh/pushwoosh-phonegap-cordova-sample#1]
These configurations in the Phonegap sample do not match what is on the Pushwoosh website. I am a paying customer having difficulties getting Pushwoosh to work correctly. What is the correct js to use? I am also never able to get a test push to work. It is why I purchased in the first place.

```
if (device.platform == "Android") {
    registerPushwooshAndroid();
}

if (device.platform == "iPhone" || device.platform == "iOS") {
    registerPushwooshIOS();
}

if (device.platform == "Win32NT") {
    registerPushwooshWP();
}
```

rawgit file has this 
pushwoosh.onDeviceReady({ projectid: "XXXXXXXXXXXXXXX", pw_appid : "XXXXX-XXXXX" });

which also isn't in the code on pushwoosh site

**Comment by shaders** [comment]
This code is a sample of the integration "all in one" supporting multiple platforms from the same code.
The website shows how the integration supposed to be done per platform.

What is the problem you experience?
Make sure you have "device" plugin enabled in your config.xml (to make "device.platform" work).
