### ISSUE TITLE
documentation no longer available

### ISSUE THREAD

**Issue by arjel** [Pushwoosh/pushwoosh-phonegap-cordova-sample#10]
The link for documentation is no longer available (https://rawgit.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/master/Documentation/files/PushNotification-js.html)

**Comment by wfhm** [comment]
@arjel documentation is moved to https://www.pushwoosh.com/docs/cordova-api-reference. The reference to rawgit is now removed.
