### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sam-suresh** [Pushwoosh/pushwoosh-phonegap-cordova-sample#3]
Hi 
I was trying to build this XDK sample. However I get this error. Am I missing anything?

ERROR (-7) from "client:upload-manager": Error in zipping package asset files: : File not found: /Library/WebServer/Apps/Intel-XDK/www/Universal_In_House.mobileprovision Error at new ComponentError (/Applications/Intel XDK.app/Contents/Resources/app.nw/core-modules/public/component-error.js:17:1122) at makeError (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/components/client/upload-manager/upload-manager.js:17:170) at getComponentError (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/components/client/upload-manager/upload-manager.js:17:265) at file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/components/client/upload-manager/upload-manager.js:17:21767 at _rejected (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/node_modules/q/q.js:844:24) at file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/node_modules/q/q.js:870:30 at Promise.when (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/node_modules/q/q.js:1122:31) at Promise.promise.promiseDispatch (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/node_modules/q/q.js:788:41) at file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/node_modules/q/q.js:604:44 at runSingle (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/node_modules/q/q.js:137:13)

**Comment by shaders** [comment]
I think you need to use correct mobile provisioning profile?

**Comment by iroshanAV** [comment]
The problem is with your config files.
