### ISSUE TITLE
Phonegap Issue

### ISSUE THREAD

**Issue by devPRS** [Pushwoosh/pushwoosh-phonegap-cordova-sample#8]
I have tried using the phonegap directory project, i changed the Pushwoosh ID and the Google ID to my own, but it still doesn't work?

It won't even build on phonegap's website either. Please assist or update the Phonegap folder to current releases.

**Comment by wfhm** [comment]
@devPRS 

Is the issue still persistent? Could you please provide us with a bit more details on it? Are you able to build your project? Are there any errors in build log or device output?
